language: node_js
node_js:
  - "0.10"
#env:
#  matrix:
#    - BROWSER=chrome  BVER=stable
#    - BROWSER=firefox BVER=stable
#matrix:
#  fast_finish: true
before_install:
  - npm install -g grunt-cli
#  - mkdir -p .travis
#  - curl -s https://codeload.github.com/rtc-io/webrtc-testing-on-travis/tar.gz/master | tar -xz --strip-components=1 --directory .travis
#  - ./.travis/setup.sh
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
before_script:
  - grunt package
#after_failure:
#  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true